### ISSUE TITLE
hubot-glink falling 

### ISSUE THREAD

**Issue by ashish1099** [knomedia/hubot-glink#1]
"HUBOT_GLINK_HOSTNAME": "10.251.102.127",
  "HUBOT_GLINK_PORT": "80",
  "HUBOT_GLINK_PROTOCOL": "http"

```
-bash-4.1$ cd hubots/hubot/ && HUBOT_SLACK_TOKEN=xoxb-xxxxxxxxxxxxxxxxxxxxx  PORT=8000 HUBOT_GLINK_HOSTNAME=10.251.102.127 HUBOT_GLINK_PORT=80 HUBOT_GLINK_PROTOCOL=http HUBOT_GLINK_TEMPLATE_DEFAULT_DELIMITER=*** bin/hubot -n 'hubot' -a shell


hubot> [Wed Apr 22 2015 15:48:33 GMT+0100 (BST)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
[Wed Apr 22 2015 15:48:33 GMT+0100 (BST)] INFO Using default redis on localhost:6379
[Wed Apr 22 2015 15:48:33 GMT+0100 (BST)] WARNING The HUBOT_AUTH_ADMIN environment variable not set
[Wed Apr 22 2015 15:48:33 GMT+0100 (BST)] INFO Data for hubot brain retrieved from Redis

hubot> hubot alias
hubot> hubot alias devaj as --from=-2hours --bgcolor=black
Shell: created alias `devaj` for `--from=-2hours --bgcolor=black`
hubot> hubot run devaj
[Wed Apr 22 2015 15:49:22 GMT+0100 (BST)] ERROR TypeError: Cannot read property 'templateDefaultDelimiter' of undefined
  at module.exports (/opt/hubot-control/hubots/hubot/node_modules/hubot-glink/node_modules/glink/lib/createTarget.js:3:32)
  at module.exports (/opt/hubot-control/hubots/hubot/node_modules/hubot-glink/node_modules/glink/lib/glink.js:8:16)
  at TextListener.callback (/opt/hubot-control/hubots/hubot/node_modules/hubot-glink/src/glink.coffee:64:7, <js>:47:21)
  at TextListener.Listener.call (/opt/hubot-control/hubots/hubot/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/opt/hubot-control/hubots/hubot/node_modules/hubot/src/robot.coffee:197:9, <js>:143:33)
  at Shell.Adapter.receive (/opt/hubot-control/hubots/hubot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at [object Object].listener (/opt/hubot-control/hubots/hubot/node_modules/hubot/src/adapters/shell.coffee:48:7, <js>:92:22)
  at [object Object].Cli.parse (/opt/hubot-control/hubots/hubot/node_modules/hubot/node_modules/cline/index.js:320:35)
  at [object Object].<anonymous> (/opt/hubot-control/hubots/hubot/node_modules/hubot/node_modules/cline/index.js:182:18)
  at [object Object].defaultFn (/opt/hubot-control/hubots/hubot/node_modules/hubot/node_modules/cline/index.js:53:13)
  at [object Object].fn (/opt/hubot-control/hubots/hubot/node_modules/hubot/node_modules/cline/index.js:217:23)
  at Interface.<anonymous> (/opt/hubot-control/hubots/hubot/node_modules/hubot/node_modules/cline/index.js:148:18)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:203:10)
  at Interface._line (readline.js:532:8)
  at Interface._ttyWrite (readline.js:761:14)
  at ReadStream.onkeypress (readline.js:100:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1096:12)
  at ReadStream.onData (readline.js:841:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:765:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at ReadStream.Readable.push (_stream_readable.js:128:10)
  at TTY.onread (net.js:529:21)

hubot>
```

**Comment by knomedia** [comment]
@ashish1099 thanks for the issue. [5f6edfb](https://github.com/knomedia/hubot-glink/commit/5f6edfba2f76dce4b25b66f59ff3e76d42d58d0e) should fix the issue. I cut a release to npm (0.0.9) :)
